return {

"Don't chart an arc under Y=0 except trace.",
"This is a hint.",
"I don't know who used this macro other than me.",
"ArcCore is the original ArcCreate.",
"I love memes.",
"Uooooohh!!",
"I know and not know at the same time.",
"Don't start your first chart with high difficulty.",
"If you want to chart a song with lots of BPM changes, good luck!",
"Beyonce 12 Jumpscare.",
"This macro was originally created by floofer... I'm sure you know that already.",
"BLUE=LEFT, RED=RIGHT",
"This hint may expanded in near future.",
"Some (if not, most) of the Chartifact's have grammar issue.\nSorry about that.",
":skull:",
"Complex arcs can be fun if used properly.",
"If you want to contribute to this, give something funny or useful.",
"I hate description cutting off the text, like, that's the reason why changelog is deprecated, I-",
"When the random isn't randoming.",
"Chartifact is a combination of Chart and Artifact which include hint, trivia, tip, etc.",
"Imagine if this macro version reached .69 that would be funny.",
"It's okay if your first chart is bad, because it's the first step to becoming a good charter.",
"Totally not having this macro idea from Phigros-",
"You have found an easter egg! What inside? Idk.",
"Shuposhupo.",
"Did you know James is Exiony?",
"Nothing is impossible, but I do nothing every day.",
"Charter when boss song being announced:",
"Hey, I heard you like slam~",
"I hope you have permission to chart this song... although most of us aren't-",
"Grode.",
"Fanmade charters always chart at high difficulty... but how about the beginner players?",
"Three (commonly) difficulties in official rhythm games are there for a reason.",
"When ArcCreate x Cytoid?",
"April Fools is everyone's (not) favorite day!",
"... no hints here",
"Is that [insert goofy aah game] reference!!?!?!?11/!?",
"Please clear your wip folder, it's unhealthy to keep it that many.",
"That moment when you have a chart block.",
"You can never have too many aliases!",
"If you feel dizzy, stop charting and sleep.",
"How the heck do I generate this much quotes in one go?",
"How to pronounce ArcCreate?\n/ɑːrkˈkriːeɪt/",
"Gimmick is annoying if it is used abusively... unless that's the intention.",
"Atsui~\nAtsukute hikarabisoouu~\nUgoite nai no ni atsuiyoo~",
"Relax and Chart.",
"There are times when you feel at the peak of your chart,\nonly to have a sharp quality drop with the next chart.",
"How do I do something?",
"Click the tap note!",
"Having Skill Issue?\nJust hit the notes in beat.",
"You're early!\nThis version of ArcCreate is preparing for release.\nPlease check back in a few decades.",
"Huohuo my beloved~",
"Never gonna give you up.",
"Kurukuru~\nKuruing~",
"Playtest your chart first before releasing it to the public.",
"Sebian Lex.",
"Don't forget to ctrl+s every 3 seconds.",
"Make a chart a couple of times before going experimental.",
"Have you found all the Chartifacts yet?",
"If you want to see every Chartifact's, just go into fun.lua.",
"Collab is one of the methods to have your chart finished.",
"There's no such thing as green arc.",
"I prefer Honkai Star Rail than Genshin Impact.",
"Use Speed to listen closely to the beat.",
"Adjust the offset first before starting to chart.",
"Say gex.",
"PATPATPATPATPATPATPATPATPATPATPATPATPATPAT\nGETHAPPYGETHAPPYGETHAPPYGETHAPPYGETHAPPYGETHAPPYGETHAPPY.",
"Title: qqqq\nComposer: qq",
"How to play arcaca :heart_eyes:",
"The arc's bounce",
"The ratio between jokes and actual useful tips is crazy.",
"To compensate / prevent overcharting, we'll put 3-4 finger section.",
"use 4090RTX to render",
"Use FFMPREG to render stuff",
"Oops! This macro has added a stacked tap in your chart, go find it.",
"I'm sorry, but the macro you've been looking for is unavailable.",
"Arc to arc the arc note.",
"susu.",
"*casually places a tap on lane 99*",
"If you want to complain about something,\nmake sure you aren't doing the same thing you're complaining about.",
"Have you considered turning off grid before rendering?",
"Arcthesia is kil...",
"Did you know..... I forgor :skull:",
"Why do some rhythm games has unusual way to do difficulty spread?",
"Your chart won't be good if there isn't any feedback.",
"Chart not working? Restart it!",
"Offical vs Fanmade has always been a controversial debate.",
"If you are someone who says 'fanmade' at official charts,\nplease stop playing, go and play fanmade charts.",
"White trace can make your trace arts more noticeable\nBut perhaps it isn't better to just duplicate it?",
"Floony's ultimate macro, has eased you from charting since 2023!",
"Has anyone even played the easy difficulty?",
"WAAHAHAHAHAHAHAHAHA!!!!",
"SkyTap is awful to manage in macros.",
"Izana arcs are bad.",
"Today is... the day where you chart something!",
"Arc body pillow when?",
"WHAT IS THAT CHART MY MAN?!?!???",
"Every Arcthesia Events after ACC#4 is :agony:",
"Always go for PM, nothing else has any meaning!",
"This is the 100th Chartifact's in array order.",
"Can we get much higher, so high~!",
"I N S A N E",
"I hate this game!\nBut I can't stop playing it!",
"You can use any charting client you want, as long as it fits you well.",
"Can I have your chart please. It's for practice.",
"Nice chart, can I steal it?",
"Make sure to use the correct arc color.",
"Trace always(?) accompanied by arcs.",
"Did you know we have Eternal before it becomes real?\nIt's called Eternity!",
"Creamy surprises (I'm talking about the milk that has a special flavor under it)",
":catexplosion:",
"I'm going insane trying to improve this macro.",
"Totally not using this for writing out my mind.",
"Every idea can disappear quickly, so make sure to note it.",
"Disappear among the sea of butterflies.\nIllusions of the past!",
"Have you noticed I've been making numerous references?",
"I have calculated the exact chart constant of your chart.\nIt's 9.8!",
"Blep",
"The grid stays ON during charting.",
"Cute chart ngl.",
"Sometimes the best songs come from underrated composers.",
"Don't determine the side by its jacket art, but by its song vibe.",
"Average tryhard players vs. casual player enjoyers.",
"I apologize that this has offended you,\nand I am sorry for the inconvenience of me NOT GIVING A-",
"Imagine charting as a real job; that would be awesome.",
"This chart makes my neurons act up.",
"Check for 1 ms hold, although it's almost impossible to do here.",
"WE ARE SO BACK!!.",
"Never ask 0th about his ASMR addiction.",
"Pentachrome is the charting group ever.",
"Never stop running, running towards to our shining future~!",
"616 Kilogram.",
"Most of the code in this macro is sto- I mean borrowed.",
"If I can stop one charter from procrastinating...",
"Try to search your name and see how many people have talked about you.",
"Oh, you're livestreaming? [Insert the most offensive slurs here].",
"If you like this Chartifact's, make sure to subscribe to our membership~",
"If you think your charts are boring, try dumping.\nDump = Placing the notes that are not in sync with the song.",
"NYEHEHEHEHEHE.",
"Charting this song fills you with determination.",
"An influential person may pass away someday, but their legacy will live on.",
"Kawai sugi DIVE!",
"Somebody (Ice)Scream!!!!",
"Welcome to my~ woooorld~",
"If your phone screen has a rough surface, don't bother playing charts with flicks.",
"Do. not. call. 'chart' a map.",
"Screw you. *Underchart your overchart*",
"Use MakeShartGood.lua on #resources, trust me.",
"Your charting style can be evident, if you kept making them.",
"Survive the ioiQ redemption as it's given you numerous TASK.",
"If you want to correct someone, make sure your tone isn't aggressive.\nSame thing with giving feedback.",
"Maybe try to crack jokes, it'll lighten both you and someone who you're talking to.",
"Hi, check out pins on #background.",
"How do I learn Blender?",
"69420 haha funny!:!:11!!!1",
"DO use Speed (on charting), it'll help you stay in rhythm!",
"Remember in offset, − for Early, or + for Late",
"uuuuuuuuaaaaaaaaaa",
"har har har har har",
"You got this!",
"The more you experience, the more you don't know.",
"I forgot to write this, uuhhhh.",
"omg, its sans from hit game undertale!!11!",
"As an AI Charting Model, I cannot provide you a way to improve your chart.",
"So true ngl.",
"How do I insert slightly suggestive Chartifacts here.",
"Laur Uptempo Hardcore Kick C2.wav",
"GENOCIDER_kick.wav",
"Glass.wav",
"Remember Jester? He’s called Pilcrow_ now, feel old yet?",
"Whatever you do, do not recall your past.",
"The end is never the end is the end is never the end is never the end is never the end...",
"Exception: Error executing macro:\nchunk_1: 420: attempt to index a nil value at...",
"You either piss in the sink or sink in the piss.",
"File not found because I felt like it.",
"<:zydemon:1227976956620964002>",
"Nah, I'd jack.",
"Floor train detected.",
"Wow, you made that pattern? Holy shit, you made the most dogshit abomination anyone’s eyes has ever laid upon.\nThe people around you are fucking blind. You see that?",
"Hey, you have a 1ms stacked arctap. I won’t tell you where though because I don’t feel like it.",
"I personally think we should ban Arccreate from the imperial measuring system.",
"Donate me 1 ArcCoin pls.",
"ahyhy jumpscare.",
"JesterJesterJesterJesterJester12345678.",
"This is the story of an ordinary man 'wusao.",
"So when are you going to finish that chart?",
"Big thanks for the community for contributing Chartifacts~!",
"C# sus4/ add11",
"BLUE ARCHIVE UOOOOOOOOOOOH-",
"Don't ask James what happened on Sunday, May 12th, 2024.",
"Do NOT let your intrusive thoughts win.",
"If you hide stuff, then it becomes inevitable until it is found.",
"WHY IS IT HOT IN HERE.",
"I am so cooked...",
"A lot of things have happened, make sure you remember the most important part.",
"UE EE UE eue EuuEUue euue u EEEUE :crying_emoji:",
"MCR#5 has left everyone broken.",
"Never ask James about Monday, 27th May 2024 Incident.",
"If someone is in panic, please suggest a serious suggestion.\nPeople might take a joke suggestion as serious one.",
"The chart cooked well!",
"Shikanoko Nokonoko Koshitantan",
"I choose the name 'James' because I don't have a cool username.\nSo now it's stuck with me.",
"Did you know 'Exiony' is a combination of Exigent and Kani (you know what I mean)\nIdk where the 'io' came from; I probably think it sounds good.",
"Most of this macro's code are 'Borrowed' from certain someone because idk how to code.",
"Can we all survive until ACC#10 happens?",
"Main event held in this server:\nACC = Arcthesia (ArcCreate?) Charting Contest\nMCR = Mystery Chart Roullete\nOFA = One for All\nSSP = Side Story Pack",
"Shikanoko Nokonoko Koshitantan~",
"You deer",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"On 19 October 2024, is where my life truly... absolutely abysmal.",
"Butterfly effect is real, if I hadn't upload that picture, this wouldn't exist.",
"I hate public speaking, anyone feel the same?",
"Ketchup is good though?",
"I love mixing stuff",
"Hey, just want to say that your chart is hot :3",
"qoq",
"Package arrived! Oh, my parents have seen it :(",
"It's good to note everything, you can't relying on what you know.",
"I forgorrrrr.",
":3c",
"Try to come back at your old chart; maybe you'll see your progress so far.",
"Having a group to work on easy things is weak.",
"my kontol lenses.",
"freakybob :tongue:",
"WHY THERE ARE SO MANY-",
"Did you know that you can close discord instead of leaving servers?",
"It's been a whule since I wrote this, I forgot the funny",
"[Insert brainrot words here]",
":3c",
"Bro I keep making a mistake :skull:",
"Nothing happened at January 19, 2025",
"YOOOOOOOOOOOOOO SHE IS REAL, SHE'S FINALLY REAL AT LAST",
"It's insane how people crying with one day without their beloved apps",
"copyfox.",
"wtf is happening on the national tv show.",
"holy shet, I think I broke this macro a couple of version ago due to me forgotting a comma",
"A random macro, ain't randoming... did I said something similar before?",
"Nothing special here",
"I wish I can draw",
"ArcCoin economy is dropping as we speak.",
"Delay-chan, STOP delaying this CHART",
"Imagine you're charting my song, hahaha",
"Is it possible to add slam in there?",
"Here's a secret trick, try using anglex/y property",
"#zy-demon-list",
"Aoka jumpscare",
"Did you know that my macro was featured in MCR#6?",
"how do you mix stuff?",
"Over 250 quotes are available in this macro, can you find them all?",
"How do you make a randomize macro, RANDOM, as in not repeating the same stuff all over and over",
"@redlix, draw me as anime girl",
"open your eyes to the truth",
"Time to steal ideas from official charts~",
"if you 'Scene.gameplayCamera.translationY = 9999999999; Scene.getNoteGroup(0). translationY = Scene.gameplayCamera.translationY'\nthe vertices of every game object will be very distorted",
"the in-game unit of Arcaea compared to ArcCreate is 100:1",
"Unity uses complex shader compiling process: it first compiles shader to DirectX bytecode\nand then use HLSLcc to transpile shader code for other platforms.",
"Before ArcCreate exists, the peasants suffered in ArcAde",
"in the fanmade scene, custom scenecontrol has 3 iterations, first one is hardwired json, second being immediate mode Lua, \nthen finally we have the keyframe based Lua",
"the arc easing: si and so, are actually SineOut easing and SineIn easing",
"Arcaea parses aff file by each characters while ArcCreate parses by line",
"Unity once wanted to add runtime fee, but got backfired so hard that\nthey have to make Unity logo splash screen optional in Personal version to please people",
"ArcCreate is based on Unity",
"This sentence you're reading is in the ...\Macros\floony\other\misc",
"put delayexplosion.gif there",
"You should use free camera and see how enwidenlanes eject the 6k lanes",
"KIMI NO AIBA GA!",
"Uma ma ma ma ma",
"Oh no, Umamusume Brainrot is infecting this chart.",
"How to handle aspect ratio? Context.screenWidth / Context.screenHeight",
"You must go on",
"If you're charting while cosplaying, I will play your charts until full combo",
"Would it be funny if I cosplay as horse girl?",
"Now let me see you dance",
"VEC2 Cymbal Crash 14.wav moment",
"WOO",
"Mambo, mambo... Omatsuri mambo♫~",
"Bakushin Bakushin Bakushinnnn",
"Hachimi~",
"Chiii~ yo chiyo chiyo chiyo no o, doooki doki doki doki dooo~? ki???\nChiii~ yo chiyo chiyo chiyo no o, suuuki suki suki shugi chiyo no o",
":wilted_rose:",
"Relax and Chart",
"Is it possible to chart on a samsung smart fridge?",
"If I spread misinformation, would it be chartmisfacts?",
"This macro is more rambling about random stuff rather than facts, ngl",
"Fun fact: you can change the skin on ArcCreate, just go to resource and search skin",
"I just realized I can code now maybe I can reduce my macro file size- /j",
"I'm unhinged and that's a fact... maybe",
"I chart, therefore I am",
"I saw a thirsty student buying a drink from a vending machine\nShe looked soda-lighted...",
"Agnes Tachyon my beloved",
"Don't start with Future 11 for your first few chart, heck, any boss-sounding song",
"There are not more than five musical notes, yet the combinations of these five give rise to more melodies than can ever be heard.",
"Those who are skilled in combat do not become angered, those who are skilled at winning do not become afraid.\nThus the wise win before they fight, while the ignorant fight to win.",
"The whole secret lies in confusing the enemy, so that he cannot fathom our real intent.",
"By reinforcing every part, he weakens every part.",
"I have heard that in war haste can be folly, but have never seen delay that was wise.",
}